name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          repository: https://github.com/LmeSzinc/AzurLaneAutoScript
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Fork
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: fork

      - name: Sync Fork
        run: |
          git config --global user.email "846187947@qq.com"
          git config --global user.name "xxy"
          cd fork
          git remote add upstream https://github.com/LmeSzinc/AzurLaneAutoScript.git
          git fetch upstream
          git merge upstream/main
          git push origin main
